name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/dependabot.yml
      - .github/workflows/ci.yml

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
